---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: push-snapshot-to-quay
spec:
  description: |-
    Tekton task to push snapshot images to quay.io using `cosign copy`. The destination for
    each image is taken from the '.spec.data.mapping' section of the release plan, in the form
    '.spec.data.mapping.components.repository', and '.spec.data.mapping.components.tags'.
    
    If `requireSuccessfulManagedRelease` is "true", the snapshot will only be pushed if it
    contains a status indicating that a managed pipeline has successfully completed.
    
    Supports tag templating with variables like {{ git_short_sha }}, {{ timestamp }}, etc.
  params:
    - name: release
      description: Namespaced name of release - should be in format "namespace/name"
      type: string
    - name: releasePlan
      description: Namespaced name of release plan - should be in format "namespace/name"
      type: string
    - name: requireSuccessfulManagedRelease
      description: Only push if the managed release status is successful
      type: string
    - name: snapshot
      description: Namespaced name of snapshot - should be in format "namespace/name"
      type: string
  steps:
    - name: check-release-status
      image: quay.io/konflux-ci/release-service-utils:066a63d25546239e79533b99c83ff521a045c819
      script: |
        #!/usr/bin/env bash
        set -eux

        # Only check release status if it will be used to determine push
        if [[ "$(params.requireSuccessfulManagedRelease)" != "true" ]]; then
          echo "No release validation required, skipping check-release-status step."
          exit 0
        fi

        # check for release status and check if a managed pipeline failed
        IFS='/' read -r RELEASE_NAMESPACE RELEASE_NAME <<< "$(params.release)"
        RELEASECONDITIONS=$(kubectl get release "$RELEASE_NAME" -n "$RELEASE_NAMESPACE" \
          -o jsonpath='{.status.conditions}')
        if [ -z "$RELEASECONDITIONS" ]; then
          echo "No release conditions found for $RELEASE_NAME in namespace $RELEASE_NAMESPACE"
          exit 1
        fi
        RELEASECONDITION=$(echo "$RELEASECONDITIONS" | jq '.[] | select(.type == "ManagedPipelineProcessed")')
        RELEASESTATUS=$(jq -r '.reason' <<< "$RELEASECONDITION")
        echo "Release status: $RELEASESTATUS"

        if [[ "$RELEASESTATUS" != *"Succeeded"* ]]; then
          echo "Release did not succeed, stopping snapshot push"
          exit 1
        fi
    - name: push-snapshot-to-quay
      image: quay.io/konflux-ci/release-service-utils:066a63d25546239e79533b99c83ff521a045c819
      script: |
        #!/usr/bin/env bash
        set -eux

        push_image() { # Expected arguments are [name, containerImage, repository, tag]
          # this task is intended to be used for quay.io
          REGISTRY=quay.io

          SOURCE_AUTH_FILE=$(mktemp)
          SOURCE_REPO=${2%%@sha256:*}
          select-oci-auth "$2" | jq -c \
            '.auths."'"$SOURCE_REPO"'" = .auths."'"$REGISTRY"'" | del(.auths."'"$REGISTRY"'")' > "$SOURCE_AUTH_FILE"

          DEST_AUTH_FILE=$(mktemp)
          # the auth key will be modified to the full repository path, so that
          # we can create a combined auth file with source and destination entries for `cosign copy` later
          select-oci-auth "$3" | jq -c \
            '.auths."'"$3"'" = .auths."'"$REGISTRY"'" | del(.auths."'"$REGISTRY"'")' > "$DEST_AUTH_FILE"

          DESTINATION_DIGEST=$(oras resolve --registry-config "$DEST_AUTH_FILE" "$3:$4" || true)
          ORIGIN_DIGEST=$(oras resolve --registry-config "$SOURCE_AUTH_FILE" "$2")

          if [[ "$DESTINATION_DIGEST" != "$ORIGIN_DIGEST" || -z "$DESTINATION_DIGEST" ]]; then
            # Create a combined auth file to enable partial oci matches to work
            DOCKER_CONFIG="$(mktemp -d)"
            export DOCKER_CONFIG

            # SC2128 - "Expanding an array without an index only gives the element in the index 0."
            # is disabled because "$item" on the next line should only have one element, so there 
            # is no need to get any index other than 0.

            # shellcheck disable=SC2128
            jq -s 'reduce .[] as $item ({}; . * $item)' \
              "$SOURCE_AUTH_FILE" "$DEST_AUTH_FILE" > "$DOCKER_CONFIG"/config.json

            cosign copy -f "$2" "$3:$4"

            echo "Pushed image $2 to repository $3:$4"
          else
            echo "Component push skipped (source digest exists at destination): $1 $2"
          fi

        }

        IFS='/' read -r "SNAPSHOT_NAMESPACE" "SNAPSHOT_NAME" <<< "$(params.snapshot)"
        SNAPSHOT_SPEC=$(kubectl get snapshot "$SNAPSHOT_NAME" -n "$SNAPSHOT_NAMESPACE" \
          -o jsonpath='{.spec}')

        IFS='/' read -r "RP_NAMESPACE" "RP_NAME" <<< "$(params.releasePlan)"
        RP_DATA=$(kubectl get releaseplan "$RP_NAME" -n "$RP_NAMESPACE" \
          -o jsonpath='{.spec.data.mapping}')

        NUM_COMPONENTS=$(jq '.components | length' <<< "$SNAPSHOT_SPEC")

        if [[ $NUM_COMPONENTS == 0 ]]; then
          echo "No components in snapshot. There needs to be at least one component" \
            "in the snapshot for this task to run."
          exit 1
        fi

        for ((i = 0; i < NUM_COMPONENTS; i++)); do
          COMPONENT=$(echo -n "$SNAPSHOT_SPEC" | jq -c --argjson i "$i" '.components[$i]')
          NAME=$(jq -r '.name' <<< "$COMPONENT")
          COMPONENT_DESTINATION=$(echo -n "$RP_DATA" | jq -c --arg c "$NAME" '.components[] | select(.name == $c)')
          [[ "$COMPONENT_DESTINATION" == "" ]] && { echo "No mapping for ${NAME}. Skipping."; continue; }
          CONTAINER_IMAGE=$(jq -r '.containerImage' <<< "$COMPONENT")
          REPOSITORY=$(jq -r '.repository' <<< "$COMPONENT_DESTINATION")

          git_sha=$(jq -r '.source.git.revision' <<< "$COMPONENT")
          all_tags=$(jq -n \
            --argjson d "$(jq '.defaults.tags//[]' <<< "$RP_DATA")" \
            --argjson t "$(jq '.tags//[]' <<< "$COMPONENT_DESTINATION")" \
            '$d+$t|unique')


          IFS=$'\n'
          for tag in $(jq -r '.[]' <<< "$all_tags"); do
            # Basic templating
            tag="${tag//\{\{ git_short_sha \}\}/${git_sha:0:7}}"
            tag="${tag//\{\{ git_sha \}\}/$git_sha}"
            # If tag needs image metadata, do inspection for all templating
            if [[ "$tag" == *"{{ timestamp }}"* || "$tag" == *"{{ release_timestamp }}"* || \
                  "$tag" == *"{{ labels."* ]]; then
              aj="$(get-image-architectures "$CONTAINER_IMAGE")"
              im="$(skopeo inspect --retry-times 3 --no-tags \
                --override-os "$(jq -rs 'map(.platform.os)|.[0]' <<< "$aj")" \
                --override-arch "$(jq -rs 'map(.platform.architecture)|.[0]' <<< "$aj")" \
                docker://"$CONTAINER_IMAGE"|jq -c)"
              tf=$(jq -r --arg d "$(jq -r '.defaults.timestampFormat//"%s"' <<< "$RP_DATA")" \
                '.timestampFormat//$d' <<< "$COMPONENT_DESTINATION")
              # Apply all templating using the image metadata
              build_date=$(jq -r '.Labels."build-date"//.Created//""' <<< "$im")
              timestamp_value=$([ -n "$build_date" ] && date -d "$build_date" "+$tf" || echo "")
              tag="${tag//\{\{ timestamp \}\}/$timestamp_value}"
              tag="${tag//\{\{ release_timestamp \}\}/$(date "+$tf")}"
              while [[ $tag =~ \{\{\ *labels\.([[:alnum:]_-]+)\ *\}\} ]]; do
                label_value=$(jq -r --arg l "${BASH_REMATCH[1]}" '.Labels[$l]//""' <<< "$im")
                tag="${tag//\{\{ labels.${BASH_REMATCH[1]} \}\}/$label_value}"
              done
            fi
            # Incrementer templating
            if [[ "$tag" == *"{{ incrementer }}"* ]]; then
              vp="${tag//\{\{ incrementer \}\}/}"
              mn=$(skopeo list-tags --retry-times 3 docker://"$REPOSITORY" 2>/dev/null | \
                jq -r '.Tags[]' | grep -E "^${vp}[0-9]+$" | sed -E "s/${vp}//" | sort -nr | head -n1)
              tag="${tag//\{\{ incrementer \}\}/$((mn + 1))}"
            fi
            push_image "$NAME" "$CONTAINER_IMAGE" "$REPOSITORY" "$tag"
          done
        done
